name: Tests

on:
  pull_request:
    paths-ignore: ['dist/**', '*.md']
  push:
    paths-ignore: ['dist/**', '*.md']

jobs:
  tests:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.2, 8.3, 8.4]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, intl, iconv
          coverage: none

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-interaction --no-suggest
          yarn install

      - name: Build
        run: yarn build

      - name: Run PHP tests
        run: vendor/bin/pest

      - name: Rust JS tests
        run: yarn test
